// Code generated by protoc-gen-go. DO NOT EDIT.
// source: port.proto

package portpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PortID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortID) Reset()         { *m = PortID{} }
func (m *PortID) String() string { return proto.CompactTextString(m) }
func (*PortID) ProtoMessage()    {}
func (*PortID) Descriptor() ([]byte, []int) {
	return fileDescriptor_729c3d36e9010a8e, []int{0}
}

func (m *PortID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortID.Unmarshal(m, b)
}
func (m *PortID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortID.Marshal(b, m, deterministic)
}
func (m *PortID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortID.Merge(m, src)
}
func (m *PortID) XXX_Size() int {
	return xxx_messageInfo_PortID.Size(m)
}
func (m *PortID) XXX_DiscardUnknown() {
	xxx_messageInfo_PortID.DiscardUnknown(m)
}

var xxx_messageInfo_PortID proto.InternalMessageInfo

func (m *PortID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Port struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Alias                []string `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions              []string `protobuf:"bytes,6,rep,name=regions,proto3" json:"regions,omitempty"`
	Coordinates          []string `protobuf:"bytes,7,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	Province             string   `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	Timezone             string   `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Unlocs               []string `protobuf:"bytes,10,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	Code                 string   `protobuf:"bytes,11,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_729c3d36e9010a8e, []int{1}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Port) GetCoordinates() []string {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *Port) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*PortID)(nil), "abyr.port.PortID")
	proto.RegisterType((*Port)(nil), "abyr.port.Port")
}

func init() { proto.RegisterFile("port.proto", fileDescriptor_729c3d36e9010a8e) }

var fileDescriptor_729c3d36e9010a8e = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x6a, 0xeb, 0x30,
	0x10, 0x85, 0x89, 0x93, 0x38, 0xf1, 0x18, 0xee, 0xa5, 0xa2, 0x84, 0xc1, 0xdd, 0x84, 0xac, 0xb2,
	0xa9, 0x02, 0x2d, 0x7d, 0x81, 0xd2, 0x52, 0xba, 0x2b, 0x29, 0xdd, 0x74, 0xe7, 0x9f, 0x69, 0x10,
	0x24, 0x1a, 0x21, 0x2b, 0x01, 0xf7, 0x21, 0xfa, 0xcc, 0x45, 0x52, 0x1c, 0x8a, 0x77, 0x3a, 0xdf,
	0x37, 0xb6, 0xd0, 0x19, 0x00, 0xc3, 0xd6, 0x49, 0x63, 0xd9, 0xb1, 0xc8, 0xca, 0xaa, 0xb3, 0xd2,
	0x83, 0xe2, 0x66, 0xc7, 0xbc, 0xdb, 0xd3, 0x26, 0x88, 0xea, 0xf8, 0xb5, 0xa1, 0x83, 0x71, 0x5d,
	0x9c, 0x5b, 0x21, 0xa4, 0x6f, 0x6c, 0xdd, 0xeb, 0x93, 0xf8, 0x07, 0x89, 0x6a, 0x70, 0xb4, 0x1c,
	0xad, 0xb3, 0x6d, 0xa2, 0x9a, 0xd5, 0x4f, 0x02, 0x13, 0xaf, 0x86, 0x42, 0x08, 0x98, 0xe8, 0xf2,
	0x40, 0x98, 0x04, 0x12, 0xce, 0x9e, 0xd5, 0xca, 0x75, 0x38, 0x8e, 0xcc, 0x9f, 0x05, 0xc2, 0xac,
	0xe6, 0xa3, 0x76, 0xb6, 0xc3, 0x49, 0xc0, 0x7d, 0x14, 0xd7, 0x30, 0x2d, 0xf7, 0xaa, 0x6c, 0x71,
	0xba, 0x1c, 0xaf, 0xb3, 0x6d, 0x0c, 0x7e, 0xde, 0xd2, 0x4e, 0xb1, 0x6e, 0x31, 0x0d, 0xbc, 0x8f,
	0x62, 0x09, 0x79, 0xcd, 0x6c, 0x1b, 0xa5, 0x4b, 0x47, 0x2d, 0xce, 0x82, 0xfd, 0x8b, 0x44, 0x01,
	0x73, 0x63, 0xf9, 0xa4, 0x74, 0x4d, 0x38, 0x0f, 0x97, 0x5d, 0xb2, 0x77, 0x4e, 0x1d, 0xe8, 0x9b,
	0x35, 0x61, 0x16, 0x5d, 0x9f, 0xc5, 0x02, 0xd2, 0xa3, 0xde, 0x73, 0xdd, 0x22, 0x84, 0x9f, 0x9e,
	0x53, 0x78, 0x0f, 0x37, 0x84, 0xf9, 0xf9, 0x3d, 0xdc, 0xd0, 0x5d, 0x0b, 0xb9, 0xef, 0xe3, 0x9d,
	0xec, 0x49, 0xd5, 0x24, 0x6e, 0x61, 0xf6, 0x42, 0x2e, 0x34, 0x74, 0x25, 0x2f, 0x6d, 0xcb, 0xd8,
	0x66, 0xf1, 0x7f, 0x80, 0xc4, 0x03, 0xc0, 0x87, 0x69, 0xc9, 0xc6, 0x2f, 0x86, 0xba, 0x58, 0xc8,
	0xb8, 0x25, 0xd9, 0x6f, 0x49, 0x3e, 0xfb, 0x2d, 0x3d, 0xe6, 0x9f, 0x99, 0xa9, 0x36, 0x7e, 0xce,
	0x54, 0x55, 0x1a, 0xe4, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x4c, 0x2f, 0x64, 0xe9,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortServiceClient interface {
	GetPort(ctx context.Context, in *PortID, opts ...grpc.CallOption) (*Port, error)
	UpsertPort(ctx context.Context, in *Port, opts ...grpc.CallOption) (*empty.Empty, error)
}

type portServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortServiceClient(cc *grpc.ClientConn) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) GetPort(ctx context.Context, in *PortID, opts ...grpc.CallOption) (*Port, error) {
	out := new(Port)
	err := c.cc.Invoke(ctx, "/abyr.port.PortService/GetPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) UpsertPort(ctx context.Context, in *Port, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/abyr.port.PortService/UpsertPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortServiceServer is the server API for PortService service.
type PortServiceServer interface {
	GetPort(context.Context, *PortID) (*Port, error)
	UpsertPort(context.Context, *Port) (*empty.Empty, error)
}

func RegisterPortServiceServer(s *grpc.Server, srv PortServiceServer) {
	s.RegisterService(&_PortService_serviceDesc, srv)
}

func _PortService_GetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).GetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abyr.port.PortService/GetPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).GetPort(ctx, req.(*PortID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_UpsertPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Port)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).UpsertPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abyr.port.PortService/UpsertPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).UpsertPort(ctx, req.(*Port))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "abyr.port.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPort",
			Handler:    _PortService_GetPort_Handler,
		},
		{
			MethodName: "UpsertPort",
			Handler:    _PortService_UpsertPort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "port.proto",
}
